### ISSUE TITLE
Cite This!  Not compatible with Firefox Quantum

### ISSUE THREAD

**Issue by klalalinn** [jamiely/citethis#3]
Do you have plans to update to meet current standards of asshole firefox?  Cite This! is the only add-on that actually works like it should!

**Comment by jamiely** [comment]
It's nice to know people use this. If I find time to update it, I will post here.

**Comment by klalalinn** [comment]
It has literally been my saving grace through college! Thanks for your hard work!

________________________________

**Comment by OspreyBait** [comment]
Oh, Man! This is the sweetest plugin for citations! I wish I knew more than markup languages...I'd be jumping in to help fast-fast. I hope you find the time, Jamie. This extensions is so great, I'd PAY for it. Seriously.

**Comment by MattDMiller** [comment]
This extension is the best citation generator I have seen! This is because Cite This! allowed editable fields in the citation generator. Which I have not seen in my search for a suitable replacement. I hope you path it quick because this thing is a life savor. I'm a current student, completed my AAS using your extension. Thanks for the awesome tool, I hope to continue using it in the future.

**Comment by jamiely** [comment]
I've submitted a version compatible with Quantum at https://addons.mozilla.org/en-US/firefox/addon/cite-this/versions/?page=1#version-0.24. Please try it out and provide feedback.

**Comment by klalalinn** [comment]
YOU ARE AMAZINGGG! Thank you so much!
